# Generated by Django 5.2.3 on 2025-06-24 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(choices=[('norte', 'Norte'), ('sur', 'Sur'), ('este', 'Este'), ('oeste', 'Oeste')], max_length=10)),
                ('tipo', models.CharField(choices=[('urbana', 'Urbana'), ('rural', 'Rural')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudadela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('num_viviendas', models.IntegerField()),
                ('num_parques', models.IntegerField()),
                ('num_edificiosR', models.IntegerField()),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenamiento.parroquia')),
            ],
        ),
    ]
